# Generated by Django 2.2.6 on 2019-10-29 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('valor', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('foto', models.ImageField(null=True, upload_to='flores')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreria.Estado')),
            ],
        ),
        migrations.DeleteModel(
            name='Floreria',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='name',
        ),
    ]
