# Generated by Django 2.2.8 on 2019-12-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0003_customuserform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='flores'),
        ),
    ]
